[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[terminal]
shell.program = "/bin/bash"
shell.args = ["-c", "${SETUP_REPO_PATH}/tmux-start.sh"]

[window]
startup_mode = "Maximized"

[keyboard]
bindings = [
  {key = "F", mods = "Alt|Shift", action = "ToggleFullscreen"}
]
